# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sdA6LZNh9SiccXsYynqLiuZw1IRtzrSS
"""

# Program without using any external library
import pandas as pd
l=w=p=s = "Python , Python , Python , Python is great and Java is also great"
q_list=[l , w , p , s]
q_list
data=pd.DataFrame(q_list, columns=['q_data'])
data

# !pip install ctgan

from ctgan import CTGANSynthesizer
import pandas as pd

data = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
data

discrete_columns = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'variety']
ctgan = CTGANSynthesizer(batch_size=50,epochs=100,verbose=False)
ctgan.fit(data,discrete_columns)
ctgan.save('ctgan-food-demand.pkl')
samples = ctgan.sample(2000)
samples

# !pip install sdv
from sdv.tabular import CTGAN

model = CTGAN(rounding=2,batch_size=50,epochs=100 )
model.fit(data)
model.save("sdv-ctgan-food-demand.pkl")
new_data = model.sample(200)
new_data.head()
from sdv.evaluation import evaluate
evaluate(new_data, data)



# !pip install table_evaluator
from table_evaluator import load_data, TableEvaluator
table_evaluator = TableEvaluator(data, new_data)
table_evaluator.visual_evaluation()

# Program without using any external library
s = "Python is great and Java is also great"
l = s.split()
k = []
for i in l:
    print(i)
    if (s.count(i)>=1 and (i not in k)):
        k.append(i)
print(' '.join(k))

l = s.split()
k = []
for i in range(len(data)):
    #print(data["q_data"][i])
    l = data["q_data"][i].split()
    print(l)



	# If condition is used to store unique string
	# in another list 'k'
    if (data["q_data"][i].count(i)>=1 and (i not in k) or (i =="great")):
		k.append(i)
print(' '.join(k))